### ISSUE TITLE
[bug]: res_prometheus does not set Content-Type header in HTTP response

### ISSUE THREAD

**Issue by Skyle974** [asterisk/asterisk#1075]
### Severity

Minor

### Versions

20.11.1

### Components/Modules

res_prometheus

### Operating Environment

Version prometeus en kubenetes par helm chart:
https://prometheus-community.github.io/helm-charts -> kube-prometheus-stack

### Frequency of Occurrence

Constant

### Issue Description

In job Target of Prometheus:
Error scraping target: non-compliant scrape target sending blank Content-Type and no fallback_scrape_protocol specified for target.

this is my job config:

```yaml
- job_name: "sip"
  scrape_interval: 60s
  metrics_path: '/metrics'
  scheme: 'http'
  static_configs:
  - targets: ["X.X.X.X:8088"]
    labels:
      app: 'asterisk'
  params:
    fallback_scrape_protocol: ["PrometheusText0.0.4"]
```
### Relevant log output

```shell

```

### Asterisk Issue Guidelines

- [x] Yes, I have read the Asterisk Issue Guidelines
